variables:
  IMAGE_NAME: "redis"
  IMAGE: "redis:latest"

stages:
  - test

dynamic-sbom:
  stage: test
  tags:
    - self-hosted
  before_script:
    - curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh
    - curl -Lo sarif-converter https://gitlab.com/ignis-build/sarif-converter/-/releases/permalink/latest/downloads/bin/sarif-converter-linux && chmod +x sarif-converter
  script:
    # Run the container so mdsbom can observe file access
    - container_id=$(docker run -q -d ${IMAGE}) && sleep 5 && docker stop $container_id
    
    # Run Docker container and filter out CVEs in components not touched at runtime
    - mdsbom scout ${IMAGE} --sca-report-out ${IMAGE_NAME}-cves-mdsbom.sarif --sca-summary-csv ${IMAGE_NAME}-report.csv
    
    # Convert Sarif to the Gitlab SAST format
    - jq 'if .runs and .runs[].results then .runs[].results[] |= if .suppressions then (.suppressions |= map(if .status == "underReview" then .status = "accepted" else . end)) else . end else . end' ${IMAGE_NAME}-cves-mdsbom.sarif > ${IMAGE_NAME}-cves-mdsbom-patched.sarif
    - ./sarif-converter --type sast ${IMAGE_NAME}-cves-mdsbom-patched.sarif gl-sast-report.json

  artifacts:
    when: always
    reports:
      sast: gl-sast-report.json
    paths:
      - '*.sarif'
      - '*.csv'
