name: Flotsam

on:
  push:
    tags: [ "*" ]
    branches:
      - 'main'
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
    
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  IMAGE_NAME: postgres:latest
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}

jobs:
  build:
    runs-on: self-hosted
    
    permissions:
      contents: read
      packages: write
      pull-requests: write
      actions: write
      security-events: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SHA }}
    
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Install docker scout
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh
      
      - name: Run docker scout
        run: |
          docker scout sbom --output ${{ env.IMAGE_NAME }}-sbom.json ${{ env.IMAGE_NAME }}
          docker scout cves --format sarif --output ${{ env.IMAGE_NAME }}-cves.sarif ${{ env.IMAGE_NAME }}

      - name: Patch docker scout SARIF report
        run : |
          jq 'walk(if type == "object" and has("startLine") and .startLine == 0 then .startLine = 1 else . end |
              if type == "object" and has("endLine") and .endLine == 0 then .endLine = 1 else . end |
              if type == "object" and has("endColumn") and .endColumn == 0 then .endColumn = 1 else . end |
              if type == "object" and has("startColumn") and .startColumn == 0 then .startColumn = 1 else . end)' ${{ env.IMAGE_NAME }}-cves.sarif > ${{ env.IMAGE_NAME }}-cves-patched.sarif

      # - name: Upload Scout SARIF result
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: ${{ env.IMAGE_NAME }}-cves-patched.sarif
      #     category: docker-scout-static

      - name: Run container
        run: |
          container_id=$(docker run -q -d ${{ env.IMAGE_NAME }})
          sleep 5
          docker stop $container_id

      - name: Run flotsam
        run: |
          flotsam report ${{ env.IMAGE_NAME }} --sbom-report-source ${{ env.IMAGE_NAME }}-sbom.json --sca-report-source ${{ env.IMAGE_NAME }}-cves.sarif --sca-report-out ${{ env.IMAGE_NAME }}-cves-flotsam.sarif --sbom-report-out ${{ env.IMAGE_NAME }}-sbom-flotsam.json

      - name: Patch docker scout SARIF report
        run : |
          jq 'walk(if type == "object" and has("startLine") and .startLine == 0 then .startLine = 1 else . end |
              if type == "object" and has("endLine") and .endLine == 0 then .endLine = 1 else . end |
              if type == "object" and has("endColumn") and .endColumn == 0 then .endColumn = 1 else . end |
              if type == "object" and has("startColumn") and .startColumn == 0 then .startColumn = 1 else . end)' ${{ env.IMAGE_NAME }}-cves-flotsam.sarif > ${{ env.IMAGE_NAME }}-cves-flotsam-patched.sarif

      - name: Upload SARIF result (flotsam)
        id: upload
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ env.IMAGE_NAME }}-cves-flotsam-patched.sarif
          category: docker-scout-runtime

      - name: Dismiss alerts
        uses: advanced-security/dismiss-alerts@v1
        with:
          # specify a 'sarif-id' and 'sarif-file'
          sarif-id: ${{ steps.upload.outputs.sarif-id }}
          sarif-file: ${{ env.IMAGE_NAME }}-cves-flotsam-patched.sarif
        env:
          GITHUB_TOKEN: ${{ github.token }} 
