name: Flotsam

on:
  push:
    tags: [ "*" ]
    branches:
      - 'main'
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
    
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  IMAGE_NAME: redis:latest
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SHA }}
    
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        continue-on-error: true
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Docker Scout
        id: docker-scout
        continue-on-error: true
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ env.IMAGE_NAME }}
          sarif-file: output.sarif
          summary: true
          
      - name: Upload Scout SARIF result
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: output.sarif
          category: scout

      - name: Run flotsam
        run: |
          sudo apt install ./flotsam_0.1.0-34724c5_amd64.deb
          flotsam report redis:latest --full-summary --sca-report-in output.sarif.output --sca-report-out sca_out.sarif

      - name: Upload SARIF result (flotsam)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sca_out.sarif
          category: flotsam
